services:
  backend:
    build: .
    restart: always
    ports:
      - "4001:4001"
    hostname: backend
    environment:
      SPRING_PROFILES_ACTIVE: docker,demo
      SPRING_ARTEMIS_BROKER_URL: tcp://activemq:61616
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/testdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - activemq
      - postgres
      - ollama
    networks:
      - my-private-ntwk

  postgres:
    image: postgres:16.14-bookworm@sha256:92620daddcd947f8d5ab5ba66e848702fe443d87fed30c4cea8e389fd78dfc55
    restart: always
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-private-ntwk
    
  frontend:
   image: slawekradzyminski/frontend:3.7.13@sha256:8f7e5cb457d277c9dd85098cb1354a646830c544d78bddca2a110ec8e1591cea
   restart: always
   ports:
     - "8081:80"
   networks:
     - my-private-ntwk

  activemq:
    image: apache/artemis:2.55.0@sha256:a192eee9c46e6352625ca9dbf0beebe4a34c363111c628bbb10c4aff1227341d
    restart: always
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
      ANONYMOUS_LOGIN: "true"
      EXTRA_ARGS: --http-host 0.0.0.0 --relax-jolokia --no-autotune --global-max-size 512M
    ports:
      - "61616:61616"
      - "8161:8161"
      - "5672:5672"
    volumes:
      - activemq-data:/var/lib/artemis-instance
    hostname: activemq
    networks:
      - my-private-ntwk

  ollama:
    image: slawekradzyminski/ollama-qwen35-2b:0.18.3@sha256:e5f0c74f0d086459837cee887574869da1703a7dbefc3cbd2702eb26b73c1953
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODELS_DIR=/root/.ollama
    networks:
      - my-private-ntwk

volumes:
  activemq-data:
  postgres-data:
  ollama-data:

networks:
  my-private-ntwk:
    driver: bridge
