package com.awesome.testing.entities.doctor;

@SuppressWarnings("unused")
public enum DoctorType {
    PEDIATRICIAN,
    PSYCHIATRIST,
    CARDIOLOGIST,
    ENDOCRINOLOGIST,
    NEUROLOGIST,
    GASTROENTEROLOGIST,
    DERMATOLOGIST,
    RADIOLOGIST,
    PATHOLOGIST,
    SURGEON,
    ANESTHESIOLOGIST,
    OPHTHALMOLOGIST,
    ORTHOPEDIST,
    UROLOGIST,
    OBSTETRICIAN_GYNECOLOGIST,
    ONCOLOGIST,
    PULMONOLOGIST,
    NEPHROLOGIST,
    ALLERGIST_IMMUNOLOGIST,
    INFECTIOUS_DISEASE_SPECIALIST,
    RHEUMATOLOGIST,
    GERIATRICIAN,
    SPORTS_MEDICINE_SPECIALIST,
    PHYSICAL_MEDICINE_REHABILITATION,
    PAIN_MANAGEMENT_SPECIALIST,
    PALLIATIVE_CARE_SPECIALIST,
    SLEEP_MEDICINE_SPECIALIST,
    PLASTIC_SURGEON,
    OTOLARYNGOLOGIST
}
