package com.awesome.testing.migration;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.postgresql.PostgreSQLContainer;

class RefreshTokenMigrationIT {

    private static final PostgreSQLContainer POSTGRES =
            new PostgreSQLContainer("postgres:16-alpine");

    @BeforeAll
    static void startPostgres() {
        POSTGRES.start();
    }

    @AfterAll
    static void stopPostgres() {
        POSTGRES.stop();
    }

    @Test
    void shouldBuildFreshSchemaWithoutPersistingRawRefreshTokens() throws Exception {
        createSchema("fresh");

        flyway("fresh", false).migrate();

        try (Connection connection = connection(); Statement statement = connection.createStatement()) {
            assertThat(columnExists(statement, "fresh", "refresh_token", "token_hash")).isTrue();
            assertThat(columnExists(statement, "fresh", "refresh_token", "family_id")).isTrue();
            assertThat(columnExists(statement, "fresh", "refresh_token", "token")).isFalse();
            assertThat(columnExists(statement, "fresh", "password_reset_token", "version")).isTrue();
        }
    }

    @Test
    void shouldHashExistingTokensWhenBaseliningProductionSchema() throws Exception {
        createSchema("legacy");
        try (Connection connection = connection(); Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE legacy.app_user (
                        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        email varchar(255) NOT NULL UNIQUE,
                        username varchar(255) NOT NULL UNIQUE
                    );
                    CREATE TABLE legacy.refresh_token (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        expires_at timestamptz NOT NULL,
                        revoked boolean NOT NULL,
                        token varchar(255) NOT NULL UNIQUE,
                        user_id integer NOT NULL REFERENCES legacy.app_user(id)
                    );
                    INSERT INTO legacy.app_user (email, username)
                    VALUES ('user@example.com', 'user');
                    INSERT INTO legacy.refresh_token (expires_at, revoked, token, user_id)
                    VALUES (CURRENT_TIMESTAMP + INTERVAL '1 day', false, 'existing-secret', 1);
                    """);
        }

        flyway("legacy", true).migrate();

        try (Connection connection = connection(); Statement statement = connection.createStatement()) {
            try (ResultSet result = statement.executeQuery(
                    "SELECT token_hash, family_id FROM legacy.refresh_token")) {
                assertThat(result.next()).isTrue();
                assertThat(result.getString("token_hash"))
                        .isEqualTo("06d11b54b8296152273332af5cf5591dc37badbfb705351b7de012b2d362bc3c");
                assertThat(result.getString("family_id")).hasSize(36);
            }
            assertThat(columnExists(statement, "legacy", "refresh_token", "token")).isFalse();
        }
    }

    private static Flyway flyway(String schema, boolean baselineOnMigrate) {
        return Flyway.configure()
                .dataSource(POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword())
                .schemas(schema)
                .defaultSchema(schema)
                .baselineOnMigrate(baselineOnMigrate)
                .baselineVersion("1")
                .locations("classpath:db/migration")
                .load();
    }

    private static void createSchema(String schema) throws Exception {
        try (Connection connection = connection(); Statement statement = connection.createStatement()) {
            statement.execute("CREATE SCHEMA " + schema);
        }
    }

    private static Connection connection() throws Exception {
        return DriverManager.getConnection(
                POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword());
    }

    private static boolean columnExists(
            Statement statement, String schema, String table, String column) throws Exception {
        try (ResultSet result = statement.executeQuery("""
                SELECT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_schema = '%s' AND table_name = '%s' AND column_name = '%s'
                )
                """.formatted(schema, table, column))) {
            result.next();
            return result.getBoolean(1);
        }
    }
}
