spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/testdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        id:
          new_generator_mappings: false
  artemis:
    mode: native
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 10
    packages:
      trust-all: true
  jackson:
    serialization:
      indent-output: true

activemq:
  destination: email

server:
  port: 4001
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: ON_PARAM
    include-exception: false

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.zalando.logbook: TRACE
    org.springframework.transaction: DEBUG
    org.springframework.jms: DEBUG
    org.springframework.orm: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n" 