spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        id:
          new_generator_mappings: false
  h2:
    console:
      enabled: true
      path: /h2-console
  
management:
  endpoint:
    health:
      show-details: always
