CREATE TABLE app_user (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_system_prompt varchar(5000),
    email varchar(255) NOT NULL UNIQUE,
    first_name varchar(255),
    last_name varchar(255),
    password varchar(255),
    tool_system_prompt varchar(5000),
    username varchar(255) NOT NULL UNIQUE,
    auth_provider varchar(100),
    email_verified boolean,
    provider_subject varchar(255),
    CONSTRAINT uk_app_user_auth_provider_subject UNIQUE (auth_provider, provider_subject)
);

CREATE TABLE products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category varchar(255) NOT NULL,
    created_at timestamp(6) NOT NULL,
    description text NOT NULL,
    image_url varchar(255),
    name varchar(255) NOT NULL,
    price numeric(10,2) NOT NULL,
    stock_quantity integer NOT NULL,
    updated_at timestamp(6) NOT NULL
);

CREATE TABLE cart_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price numeric(10,2) NOT NULL,
    quantity integer NOT NULL,
    username varchar(255) NOT NULL,
    version bigint,
    product_id bigint NOT NULL REFERENCES products(id),
    CONSTRAINT uk_cart_items_username_product UNIQUE (username, product_id)
);

CREATE TABLE orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    city varchar(255),
    country varchar(255),
    state varchar(255),
    street varchar(255),
    zip_code varchar(255),
    status varchar(255) NOT NULL CHECK (status IN ('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    total_amount numeric(10,2) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    username varchar(255) NOT NULL
);

CREATE TABLE order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price numeric(10,2) NOT NULL,
    quantity integer NOT NULL,
    order_id bigint NOT NULL REFERENCES orders(id),
    product_id bigint NOT NULL REFERENCES products(id)
);

CREATE TABLE email_event (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL,
    failure_reason varchar(1000),
    recipient_email varchar(255) NOT NULL,
    status varchar(255) NOT NULL CHECK (status IN ('QUEUED', 'SENT_TO_SMTP_SINK', 'FAILED')),
    type varchar(255) NOT NULL CHECK (type IN ('GENERIC', 'PASSWORD_RESET_REQUESTED', 'PASSWORD_RESET_CONFIRMED')),
    updated_at timestamptz NOT NULL,
    user_id integer NOT NULL REFERENCES app_user(id)
);

CREATE TABLE mfa_challenge (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consumed_at timestamptz,
    created_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    token_hash varchar(64) NOT NULL UNIQUE,
    version bigint NOT NULL,
    user_id integer NOT NULL REFERENCES app_user(id)
);

CREATE TABLE mfa_credential (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    confirmed_at timestamptz,
    created_at timestamptz NOT NULL,
    enabled boolean NOT NULL,
    last_accepted_time_step bigint,
    secret_ciphertext varchar(2048) NOT NULL,
    setup_expires_at timestamptz NOT NULL,
    version bigint NOT NULL,
    user_id integer NOT NULL UNIQUE REFERENCES app_user(id)
);

CREATE TABLE mfa_recovery_code (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL,
    selector varchar(8) NOT NULL,
    used_at timestamptz,
    verifier_hash varchar(255) NOT NULL,
    version bigint NOT NULL,
    credential_id bigint NOT NULL REFERENCES mfa_credential(id),
    CONSTRAINT uk_mfa_recovery_code_credential_selector UNIQUE (credential_id, selector)
);

CREATE TABLE password_reset_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consumed_at timestamptz,
    expires_at timestamptz NOT NULL,
    request_ip varchar(64),
    requested_at timestamptz NOT NULL,
    token_hash varchar(128) NOT NULL UNIQUE,
    user_agent varchar(255),
    user_id integer NOT NULL REFERENCES app_user(id)
);

CREATE TABLE refresh_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expires_at timestamptz NOT NULL,
    revoked boolean NOT NULL,
    token varchar(255) NOT NULL UNIQUE,
    user_id integer NOT NULL REFERENCES app_user(id)
);

CREATE TABLE traffic_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_session_id varchar(128),
    correlation_id varchar(64) NOT NULL UNIQUE,
    duration_ms bigint NOT NULL,
    method varchar(16) NOT NULL,
    path varchar(1024) NOT NULL,
    query_string varchar(2000),
    request_body oid,
    request_headers oid,
    response_body oid,
    response_headers oid,
    status integer NOT NULL,
    "timestamp" timestamptz NOT NULL,
    request_content_type varchar(255),
    response_content_type varchar(255),
    request_body_truncated boolean DEFAULT false NOT NULL,
    request_body_original_length integer DEFAULT 0 NOT NULL,
    request_body_stored_length integer DEFAULT 0 NOT NULL,
    response_body_truncated boolean DEFAULT false NOT NULL,
    response_body_original_length integer DEFAULT 0 NOT NULL,
    response_body_stored_length integer DEFAULT 0 NOT NULL
);

CREATE INDEX idx_traffic_log_client_session_id ON traffic_log (client_session_id);
CREATE INDEX idx_traffic_log_timestamp ON traffic_log ("timestamp");

CREATE TABLE user_entity_roles (
    user_entity_id integer NOT NULL REFERENCES app_user(id),
    roles smallint CHECK (roles BETWEEN 0 AND 1)
);
