DO $migration$
BEGIN
    IF to_regclass('products') IS NOT NULL AND to_regclass('orders') IS NOT NULL THEN
        ALTER TABLE products ADD COLUMN version bigint NOT NULL DEFAULT 0;
        ALTER TABLE products
            ADD CONSTRAINT ck_products_stock_nonnegative CHECK (stock_quantity >= 0);

        ALTER TABLE orders
            ADD COLUMN inventory_state varchar(32) NOT NULL DEFAULT 'LEGACY_UNTRACKED';
        ALTER TABLE orders
            ADD CONSTRAINT ck_orders_inventory_state
                CHECK (inventory_state IN ('DEDUCTED', 'RESTORED', 'LEGACY_UNTRACKED'));

        CREATE TABLE inventory_movements (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            product_id bigint NOT NULL REFERENCES products(id) ON DELETE CASCADE,
            order_id bigint REFERENCES orders(id) ON DELETE SET NULL,
            type varchar(32) NOT NULL
                CHECK (type IN ('INITIAL_STOCK', 'ADMIN_ADJUSTMENT', 'ORDER_DEDUCTED', 'ORDER_RESTORED')),
            delta integer NOT NULL CHECK (delta <> 0),
            quantity_after integer NOT NULL CHECK (quantity_after >= 0),
            actor varchar(255) NOT NULL,
            reason varchar(500) NOT NULL,
            request_id uuid,
            created_at timestamp(6) NOT NULL,
            CONSTRAINT uk_inventory_product_request UNIQUE (product_id, request_id)
        );

        CREATE INDEX idx_inventory_product_created
            ON inventory_movements(product_id, created_at);
        CREATE INDEX idx_inventory_order ON inventory_movements(order_id);
    END IF;
END
$migration$;
