name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Run tests
      run: ./mvnw clean package

  runDev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Run dev build
      run: bash ./run-app.sh
  
  runDocker:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:stable
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
    steps:
    - uses: actions/checkout@v4
    - name: Build and run Docker Compose
      run: bash ./run-docker-compose.sh